version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "charliestrawn"
    assignees:
      - "charliestrawn"
    commit-message:
      prefix: "deps"
      include: "scope"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "charliestrawn"
    assignees:
      - "charliestrawn"
    commit-message:
      prefix: "ci"
      include: "scope"